name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: lukka/get-cmake@v3
    - name: Build
      run: 
        cmake -Bbuild -H.
        cmake --build build --config Release
    - name: Generate Doxygen Documentation
      run: doxygen Doxyfile
